# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Eisner | beisner
name: Ben Eisner
job_title: Software Engineer and Research Enthusiast
email: ben.a.eisner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a software engineer and research enthusiast with experience 
  building web servers, desktop applications, and embedded systems.
  I am interested in machine learning research and applications of AI
  in robotics, and always looking for new projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beisner.me" # the base hostname & protocol for your site
twitter_username: benaeisner
github_username:  beneisner
linkedin_username: beneisner
resume_path: files/Ben_Eisner_Resume_11_2_16.pdf

# Build settings
markdown: kramdown
