# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Eisner | beisner
name: Ben Eisner
job_title: ML + Robotics Researcher
email: ben.a.eisner@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ML + Robotics Researcher <br>
  Ph.D. Student in Robotics @ CMU <br>
  Ex-Google, Ex-Samsung, Ex-Microsoft.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beisner.me" # the base hostname & protocol for your site
twitter_username: benaeisner
github_username: beneisner
linkedin_username: beneisner
scholar_title: Google Scholar
thesis_path: files/ben_eisner_ugrad_thesis_2017.pdf
cv_path: files/ben_eisner_cv_2021_02_28.pdf
nsf_personal_path: files/nsf_grfp_personal_statement_2019.pdf
nsf_research_path: files/nsf_grfp_research_plan_2019.pdf

# Build settings
markdown: kramdown
